# Generated by Django 5.1.2 on 2024-10-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emoji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emoji',
            old_name='acess_code',
            new_name='access_code',
        ),
    ]
