# Generated by Django 5.1.2 on 2024-10-15 07:26

import banjo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_emoji_access_code_emoji_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emoji',
            name='x_coordinates',
        ),
        migrations.RemoveField(
            model_name='emoji',
            name='y_coordinates',
        ),
        migrations.CreateModel(
            name='Canva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', banjo.models.IntegerField(default=0)),
                ('emojis', banjo.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emoji')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
