# Generated by Django 5.1.2 on 2024-10-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_emoji_x_coordinates_emoji_y_coordinates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Canva',
        ),
    ]
