# Generated by Django 5.1.2 on 2024-10-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_emoji_x_coordinates_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Canva',
        ),
    ]
