# Generated by Django 5.1.2 on 2024-10-15 12:25

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_canva'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='x_coordinates',
            field=banjo.models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emoji',
            name='y_coordinates',
            field=banjo.models.IntegerField(default=0),
        ),
    ]
