# Generated by Django 5.1.2 on 2024-10-17 08:34

import banjo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_emoji_x_coordinates_emoji_y_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', banjo.models.IntegerField(default=0)),
                ('emojis', banjo.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emoji')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
