# Generated by Django 5.1.2 on 2024-10-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emoji',
            name='x_coordinates',
        ),
        migrations.RemoveField(
            model_name='emoji',
            name='y_coordinates',
        ),
    ]
