# Generated by Django 5.1.2 on 2024-10-19 13:12

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_canva_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canva',
            name='popularity_percentage',
            field=banjo.models.IntegerField(default=0),
        ),
    ]
