# Generated by Django 5.1.2 on 2024-10-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_canva_created_time_remove_canva_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emoji',
            name='username',
        ),
        migrations.RemoveField(
            model_name='emoji',
            name='x_coordinates',
        ),
        migrations.RemoveField(
            model_name='emoji',
            name='y_coordinates',
        ),
    ]
