# Generated by Django 5.1.2 on 2024-10-21 09:55

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_canva_popularity_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='input_time',
            field=banjo.models.StringField(default=''),
        ),
    ]
