# Generated by Django 5.1.2 on 2024-10-21 10:17

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_emoji_input_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canva',
            name='time_period',
        ),
        migrations.AddField(
            model_name='emoji',
            name='time_period',
            field=banjo.models.StringField(default=''),
        ),
    ]
