# Generated by Django 5.1.2 on 2024-10-17 13:17

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_canva_created_time_remove_canva_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canva',
            name='created_time',
            field=banjo.models.StringField(default=''),
        ),
        migrations.AddField(
            model_name='canva',
            name='creator',
            field=banjo.models.StringField(default=''),
        ),
        migrations.AddField(
            model_name='canva',
            name='popularity_percentage',
            field=banjo.models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='canva',
            name='time_period',
            field=banjo.models.StringField(default=''),
        ),
        migrations.AddField(
            model_name='canva',
            name='view',
            field=banjo.models.IntegerField(default=0),
        ),
    ]
